# In your static/admin/config.yml file

backend:
  name: github
  repo: lcdave/praxis-menssana

media_folder: static/assets
public_folder: assets

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.md"
        fields:
          - - {label: Seo Titel, name: seoTitle, widget: string}
              - {label: Seo Beschreibung, name: seoDescription, widget: string}
              - {label: Seo Stichwörter, name: seoKeywords, widget: string}
          - {label: Kopfbild, name: headerimage, widget: image}
          - {label: Kopfzeile Titel, name: headertitle, widget: string}
          - {label: Kopfzeile Zitat, name: headerquote, widget: string}
          - {label: Intro Text Titel, name: introtitle, widget: string}
          - {label: Intro Text Inhalt, name: introtext, widget: string}
          - {label: Karte 1 Titel, name: card_1_title, widget: string}
          - {label: Karte 1 Beschreibung, name: card_1_content, widget: string}
          - {label: Karte 1 Link, name: card_1_link, widget: string}
      - label: "Hypnosetherapie"
        name: "hypnosetherapie"
        file: "content/hypnosetherapie.md"
        fields:
          - {label: Seo Titel, name: seoTitle, widget: string}
          - {label: Seo Beschreibung, name: seoDescription, widget: string}
          - {label: Seo Stichwörter, name: seoKeywords, widget: string}
          - {label: Kopfbild, name: headerimage, widget: image}
          - {label: Kopfzeile Titel, name: headertitle, widget: string}
          - {label: Zitat, name: quote, widget: string}
      - label: "AengstePhobien"
        name: "phobien"
        file: "content/aengste-phobien.md"
        fields:
          - {label: Seo Titel, name: seoTitle, widget: string}
          - {label: Seo Beschreibung, name: seoDescription, widget: string}
          - {label: Seo Stichwörter, name: seoKeywords, widget: string}
          - {label: Kopfbild, name: headerimage, widget: image}
          - {label: Kopfzeile Titel, name: headertitle, widget: string}
      - label: "Termin vereinbaren"
        name: "terminPage"
        file: "content/termin.md"
        fields:
          - {label: Seo Titel, name: seoTitle, widget: string}
          - {label: Seo Beschreibung, name: seoDescription, widget: string}
          - {label: Seo Stichwörter, name: seoKeywords, widget: string}
          - {label: Kopfbild, name: headerimage, widget: image}
          - {label: Kopfzeile Titel, name: headertitle, widget: string}
        collections:
          - name: "text"
            label: "Text"
            folder: "content/termin/"
            create: true
            fields:
              - {label: Inhalt, name: body, widget: markdown}
      - label: "Über mich"
        name: "uebermich"
        file: "content/uebermich.md"
        fields:
          - {label: Seo Titel, name: seoTitle, widget: string}
          - {label: Seo Beschreibung, name: seoDescription, widget: string}
          - {label: Seo Stichwörter, name: seoKeywords, widget: string}
          - {label: Kopfbild, name: headerimage, widget: image}
          - {label: Kopfzeile Titel, name: headertitle, widget: string}
          - {label: Profil Bild, name: profile_img, widget: image}
