# In your static/admin/config.yml file

backend:
  name: github
  repo: lcdave/praxis-menssana

media_folder: static/assets
public_folder: assets

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.md"
        fields:
          - {label: Kopfzeile Bild, name: headerimage, widget: image}
          - {label: Kopfzeile Titel, name: headertitle, widget: string}
          - {label: Kopfzeile Zitat, name: headerquote, widget: string}
